[package]
name = "vanth"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
serde.workspace = true
serde_json.workspace = true
