[package]
name = "vanth_cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
serde_json.workspace = true
vanth = { path = "../vanth" }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile = { workspace = true }
